### ISSUE TITLE
Compiling Fluidsynth

### ISSUE THREAD

**Issue by charlesneimog** [porres/pd-fluidsynth#9]
Here's fluidsynth for Windows 64, don't you want to release it?

[Fluidsynth.zip](https://github.com/porres/pd-fluidsynth/files/8513011/Fluidsynth.zip)
!

**Comment by porres** [comment]
certeza se funciona em outras maquinas?

**Comment by porres** [comment]
pior que funcionou na minha virtual machine! Já o que eu compilei no mac não rolou! caceta... to tentando ver qual o problema e incluir logo isso na ELSE.

**Comment by porres** [comment]
vc pode descrever os passos pra compilar e tudo mais? e por favor, não mude o help e mantenha o prefixo 'else/'

**Comment by porres** [comment]
renaming this issue as @charlesneimog was able to build this for windows but I'm having issues to build it for mac

**Comment by charlesneimog** [comment]
Eu consegui compilar pra Mac, eu fiz um fork, tá lá pra Mac. No Mac que testei e deu boa! 

Colocando no else seria ótimo e muito mais fácil pro pessoal instalar. 

No windows vc precisa colocar várias Dll na pasta, da pra colocar isso via deken TB?

No Linux que achei meio estranho e não sei bem cm está! Eu só testei em máquina virtual e n consegui anotar os passos ahahha! Mas o objeto está compilado!

**Comment by porres** [comment]
what version of fluisdynth are you using? I tried with the latest 2.2.7

**Comment by porres** [comment]
> Eu consegui compilar pra Mac, eu fiz um fork, tá lá pra Mac. No Mac que testei deu boa!

puta que pariu caralho funcionou, porra! Como você fez essa merda? :) explica!!! To vendo que vc usou a versão 2.2.6

**Comment by porres** [comment]
tenta recompilar por favor, vamos atualizar pro ultimo 2.2.7, me passa exatamente qual é o seu sistema e como vc fez. Vamos testar tambem compilando pra apple silicon!!!

**Comment by charlesneimog** [comment]
> tenta recompilar por favor, vamos atualizar pro ultimo 2.2.7, me passa exatamente qual é o seu sistema e como vc fez. Vamos testar tambem compilando pra apple silicon!!!

Blz, vou pedir pro meu amigo o Mac dele hahahaha, eu realmente não lembro de ter nenhum problema, eu só segui os seus passos (por isso estranhei o por que de vc não colocar os releases ou no deken).

**Comment by porres** [comment]
eu nao tinha colocado ainda pq tem bugs a resolver, olha os outros issues!

mas agora chegou a hora de colocar... eu queria primeiro incluir um objeto de 'score' e acabei de fazer isso na ultima versao, agora quero usar o score com o fluidsynth

**Comment by porres** [comment]
seguindo os meus passos eu acabo com uma enormidade de dependencias, veja a foto aqui 

<img width="269" alt="Screen Shot 2022-04-30 at 15 41 43" src="https://user-images.githubusercontent.com/5360142/166118499-fa5cc643-c2d0-4158-96bd-b07f4082160c.png">

queria saber como vc conseguiu ficar com apenas uma e ainda fazer funcionar!!!

**Comment by charlesneimog** [comment]
Eu acho que é porque instalei o fluidsynth via `apt-get install` e dai compilei. O seu mac deve ter o `fluidsynth` instalado, por isso funciona. Eu acho que se vc escrever `apt get remove fluidsynth` não vai funcionar. (Eu to fazendo isso de cabeça, não tenho certeza se é esse comando).

**Comment by charlesneimog** [comment]
So pra dizer que fiz o player microtonal pro OM usando o PD pra não ter que usar o Max e o player que o pessoal usa via max (super pesado), eu não tive nenhum problema. Funciona muitooo bem.

**Comment by porres** [comment]
entao, na real a tua versão pra mac nao ta funcionando nao...

**Comment by porres** [comment]
acho que funcionou pq misturou o seu com o meu... mas tentando apenas com o seu acontece esse erro

/Users/ale/Downloads/Fluidsynth_MacOS/./fluidsynth~.pd_darwin: dlopen(/Users/ale/Downloads/Fluidsynth_MacOS/./fluidsynth~.pd_darwin, 10): Library not loaded: /usr/local/opt/fluid-synth/lib/libfluidsynth.3.dylib
  Referenced from: /Users/ale/Downloads/Fluidsynth_MacOS/./fluidsynth~.pd_darwin
  Reason: image not found

**Comment by porres** [comment]
ou seja, a sua forma pede que se ache a lib no local... "/usr/local/opt/" isso tá errado

**Comment by porres** [comment]
já o meu erro da forma que compilei dá isso aqui

Library not loaded: @loader_path/libfluidsynth.3.dylib
  Referenced from: /Users/ale/Downloads/fluidsynth~/./fluidsynth~.pd_darwin
  Reason: no suitable image found.  Did find:
	/Users/ale/Downloads/fluidsynth~/./libfluidsynth.3.dylib: cannot load 'libfluidsynth.3.dylib' (load command 0x80000034 is unknown)
	/Users/ale/Downloads/fluidsynth~/libfluidsynth.3.dylib: cannot load 'libfluidsynth.3.dylib' (load command 0x80000034 is unknown)

**Comment by porres** [comment]
bom, nao sei o que acontece que agora nao funciona mais de jeito nenhum aqui... to meio confuso, posso jurar que tinha funcionado aqui, mas aparentemente nao, talvez numa outra maquina aqui... doideira...

**Comment by porres** [comment]
sim, foi na outra maquina que tem o fluisynth instalado na raiz ali onde ele pede, ou seja, não é legal, não é assim que eu quero :) pelo menos o windows parece funcionar, já que rodou na virtual machine... mas a tua versão pra mac parece estar pior que a minha!

**Comment by charlesneimog** [comment]
Estranho porres, por que aqui está funcionando!

![Captura de Tela 2022-04-30 às 16 12 09](https://user-images.githubusercontent.com/31707161/166119556-f9689fe1-0fe6-41d3-b3c0-946047dda56e.png)

**Comment by charlesneimog** [comment]
É isso mesmo, pra ele funcionar no MAC vc precisa do `brew install fluidsynth`, sem isso não funciona mesmo.

**Comment by charlesneimog** [comment]
Sem o brew install fluidsynth
![Captura de Tela 2022-04-30 às 16 19 28](https://user-images.githubusercontent.com/31707161/166119682-425a7aee-e584-42df-9420-77966d6479c8.png)


E depois do brew install fluidsynth.

![Captura de Tela 2022-04-30 às 16 22 15](https://user-images.githubusercontent.com/31707161/166119743-ba0696ef-78f3-447b-b056-e648fc4cfb8b.png)

a else nao está instalada aqui!

**Comment by charlesneimog** [comment]
Eu acho (eu nao sei absolutamente nada de C), que para usar o fluidsynth sem tem bibliotecas dinamicas vc vai precisar mudar o seu código, alterar de bibliotecas dinamicas para bibliotecas estáticas.  https://stackoverflow.com/questions/1705961/how-to-link-to-a-static-library-in-c ou isso aqui https://stackoverflow.com/questions/11344965/how-to-include-static-library-in-makefile.

Desculpa se você já sabe disso!

**Comment by porres** [comment]
tentando compilar de novo em outro mac

[fluidsynth~.zip](https://github.com/porres/pd-fluidsynth/files/8597714/fluidsynth.zip)

**Comment by charlesneimog** [comment]
Essa versão funcionou pra mim!

![Captura de Tela 2022-04-30 às 16 50 48](https://user-images.githubusercontent.com/31707161/166120680-5fd51ddb-0e00-41c3-ad02-b22b7ec0ed0d.png)

Eu to no Big Sur!

**Comment by porres** [comment]
pra mim tb funcionou, nao sei pq... compilei num mac air em vez do pro... vou ter que investigar a diferença... o problema é que no air eu nao consigo compilar pra appple silicon

**Comment by charlesneimog** [comment]
Pois é, o que to usando tb é intel

**Comment by porres** [comment]
no pro eu vejo isso no terminal depois de compilar 

++++ info: linking objects in fluidsynth~.pd_darwin for lib fluidsynth~
cc -undefined suppress -flat_namespace -bundle  -arch x86_64 -mmacosx-version-min=10.6  -o fluidsynth~.pd_darwin fluidsynth~.o  -lc -lfluidsynth  
ld: warning: dylib (/usr/local/lib/libfluidsynth.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libgthread-2.0.0.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libglib-2.0.0.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libintl.8.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libportaudio.2.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libsndfile.1.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/opt/readline/lib/libreadline.8.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libpcre.1.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libglib-2.0.0.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libFLAC.8.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libvorbis.0.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libvorbisenc.2.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libopus.0.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libogg.0.dylib) was built for newer macOS version (12.0) than being linked (10.6)
ld: warning: dylib (/usr/local/lib/libvorbis.0.dylib) was built for newer macOS version (12.0) than being linked (10.6)
++++info: target all in lib fluidsynth~ completed

**Comment by porres** [comment]
já no air eu não tenho esses avisos... deve ser isso

**Comment by porres** [comment]
eu por mim nao tinha uma caralhada de lib dinamica, mas quando tratei desse assunto há mais de um ano na lista, nao lembro pq, ficamos assim mesmo...

**Comment by porres** [comment]
To build for arm64, you need a new enough Xcode (12.2 I believe) and that's it. You can cross-compile on an x86_64 machine for arm64 and vice-versa.

will see if I can install Xcode on mojave...

**Comment by charlesneimog** [comment]
Mas tá funcionando no Mac pro? Esse compilado? 

Outra, vc vê problema em distribuir assim?

**Comment by porres** [comment]
no macbook pro eu tenho duas partições, uma com o monterey onde eu instalei o fluidsynth e outra com o mojave. No monterey funciona o que eu compilei no monterey, mas tb pq ele tb já tem o fluidsynth... pra testar o que eu compilei no mojave no monterey eu teria que deletar o fluidsynth, como faço?

Pelo menos vc confirma que funciona no big sur né...

eu vejo problema de ter um que apenas funcione no 10.12! com certeza... quero um que funcione em mais sistemas e acho que o do mojave deve funcionar sim no monterey, mas preciso desinstalar o fluidsynth e testar.

Agora, quero criar um binário 'fat' que funcione tb em arm, nesse caso eu não posso compilar no mojave, terei que compilar no monterey, e aí eu não sei como é que funciona essa parada, deve ser uma dor de cabeça só

resolvendo como faz pra ter um mesmo download que funcione pra mac intel e arm, já era...

na pior das hipóteses eu crio pacotes diferentes

**Comment by porres** [comment]
agora eu tinha que tentar compilar pra arm tb...

**Comment by porres** [comment]
>pra testar o que eu compilei no mojave no monterey eu teria que deletar o fluidsynth, como faço?

fiz e funcionou...

**Comment by charlesneimog** [comment]
>  pra testar o que eu compilei no mojave no monterey eu teria que deletar o fluidsynth, como faço?

Por aqui eu fiz: `brew uninstall fluidsynth`,
> 
> Pelo menos vc confirma que funciona no big sur né...
Sim sim, 

> resolvendo como faz pra ter um mesmo download que funcione pra mac intel e arm, já era...

O mac será que não reconhece qual é pra qual não?

**Comment by charlesneimog** [comment]
Então só falta o M1 né?

**Comment by porres** [comment]
falta testarem no M1, eu juntei o binário que eu compilei no monterey que junta pra intel e arm, usei as libs do mojave em vez do monterey, funciona no monterey intel, precisa ver se funciona no M1

deve funcionar no air certeza, se não funcionar eu escrevo aqui embaixo "PQP"

vou pedir pra galera testar no M1

https://github.com/porres/pd-fluidsynth/releases/tag/0.0.0-test

**Comment by porres** [comment]
PUUUUTA QUE PARIIIIIU

**Comment by charlesneimog** [comment]
Acho que vc vai ter que arrumar as dylib compiladas pro M1

**Comment by porres** [comment]
entendeu que puta que pariu é ruim né? :)

**Comment by charlesneimog** [comment]
AHAHAHHA sim sim ahahha

**Comment by porres** [comment]
na verdade foi o mesmo problema de antes, se eu compilo no monterey com as libs dinamias do fluidsynth de lá, não rola abrir no mojave...

**Comment by charlesneimog** [comment]
Mas vlw pelo trabalho, vai ser muitooo útil pro pessoal da microtonalidade!

**Comment by charlesneimog** [comment]
Por que essa versão e mais precisa que a do Max, que só aceita 1/16 de tom. Pelo oq entendi essa daí tem maior. Mas ainda tô testando. 


Posso fazer um player microtonal melhor pro OM. Ahaha

**Comment by charlesneimog** [comment]
Segue os patches se quiser dar uma olhada...


https://github.com/charlesneimog/OM-CKN/tree/master/resources%2FPd-Patches

**Comment by porres** [comment]
é com o pitch bend, é isso?

**Comment by charlesneimog** [comment]
Sobre a versão `Linux`. Por aqui só roda se vc instalar o `fluidsynth` primeiro com `apt-get install fluidsynth`. Como vc consegue as bibliotecas dinamicas? Vou ver se consigo todas pra fazer já a pasta no Linux tb.

**Comment by charlesneimog** [comment]
> é com o pitch bend, é isso?

Isso!!!

**Comment by porres** [comment]
aproveita q vc vai usar a else pro fluid~ e desencana da cyclone :)

**Comment by charlesneimog** [comment]
Descobri esses dias essa link (citado no PlugData) onde compara as da os objetos que fazem coisas parecidas. Vou fazer isso!

**Comment by porres** [comment]
sim, eu que fiz, botei no readme da else tb

**Comment by charlesneimog** [comment]
Eu testei a versão do Linux (no Ubuntu), e só é necessário o `libfluidsynth.so.3` que já está naquele fork que fiz. Então a versão do linux 64 tb já ta funcionando sem a necessidade de instalar o fluidsynth via `apt-get install fluidsynth`. 

https://github.com/charlesneimog/pd-fluidsynth/releases/download/v0.0.1/fluidsynth_Linux64.zip

**Comment by porres** [comment]
a questão é, cada desgraça de versão de linux vai precisar de uma porrinha diferente?

**Comment by charlesneimog** [comment]
Essa versão deve funcionar em todos as versões baseadas em Debian. As pessoas que usam outra versões, acredito, não vão ter problemas para compilar pra eles. (Eu tb n sei cm funciona essas coisas).

**Comment by porres** [comment]
vou fechar isso aqui e vamos discutir agora aqui ---> https://github.com/porres/pd-else/issues/1243

vc consegue discutir em inglês?

**Comment by charlesneimog** [comment]
Sim sim, tranquilo!

**Comment by porres** [comment]
@charlesneimog 

Tu queria microtonalidade Féladaputa????? Toma aqui essa porra com resolução de -100 a 100 cents!!!

![Screen Shot 2022-05-03 at 23 12 38](https://user-images.githubusercontent.com/5360142/166614747-194cc67a-3d28-4ce0-8fcc-25f90524fe95.png)

**Comment by charlesneimog** [comment]
Orrrraaaaaa vc fez uma mensagemmmm só pra centssss. Muitoooo massa!!! 

Nossaaa, muitooo massaaa mesmo!

**Comment by porres** [comment]
já tem embutido cara!!! Tem muita coisa, dá até pra definir escalas!!!!

tem delay, tem reverb, tem vibrato, tem uma porrada de coisa embutida no fluidsynth, é absurdo!!! Olha aqui a partir da pág 31!!! http://www.synthfont.com/sfspec24.pdf

**Comment by porres** [comment]
no caso tem esse "52 fineTune"

"This is a pitch offset, in cents, which should be applied to the note. It is additive
with coarseTune. A positive value indicates the sound is reproduced at a higher
pitch; a negative value indicates a lower pitch. For example, a Fine Tuning value of -
5 would cause the sound to be reproduced five cents flat."

e ele meio que aceita qualquer valor. To pensando em criar uma mensagem "tranp" de transposição mesmo e dizer que a entrada é em cents. 

Tem também esse "56 scaleTuning" onde vc define um passo em cents (ou seja, rola quartos de tom, etc, pelo menos foi o que eu enendi, ainda não testei) This parameter represents the degree to which MIDI key number influences pitch. A
value of zero indicates that MIDI key number has no effect on pitch; a value of 100
represents the usual tempered semitone scale. 

e a galera do ceammc parece que define escala, ou seja, transposições pra cada nota, vou ver como eles fazem isso...  https://github.com/uliss/pure-data/blob/ceammc/ceammc/ext/src/misc/fluid.cpp#L717

**Comment by porres** [comment]
as funções de afinação tão aqui https://www.fluidsynth.org/api/group__tuning.html

**Comment by porres** [comment]
achei o que o ceammc usa, tá aqui... é um esquema que vc define as 12 notas de uma oitava https://www.fluidsynth.org/api/group__tuning.html#ga00a6c50115555bda84578d0f994492b1

mas porra PUUUUUUUUUTA QUE PARIU OLHA ISSO AQUI https://www.fluidsynth.org/api/group__tuning.html#ga50d0a28c3699a8d03cbadfd06f84a2eb

AQUI VC DEFINE A NOTA QUE VC QUER PRA CAAAAAAAADA UMA DAS 128 NOTAS MIDI!!!!!!!

**Comment by porres** [comment]
TOOOOOMA MICROTONALIDADE FELADAPUUUTA!!!!!!!!!!!!

**Comment by charlesneimog** [comment]
Caraca isso é bizarro, o pessoal daqueles grupos de microtonalidade (eu inclusive) no Face vão pirar, eles sempre ficam discutindo qual o melhor VST para microtonalidade HAHAHAHAHAHA.

**Comment by porres** [comment]
vou dar um curso de microtonalidade no Pd, topa? :)

**Comment by charlesneimog** [comment]
> vou dar um curso de microtonalidade no Pd, topa? :)

Opaaa, topo sim! Só falar!!!
